# Continous Integration setup for SU2.
# Tests on the develop branch in both serial and parallel.

dist: trusty
sudo: required

language: python

compiler:
    - gcc

notifications:
    email:
        recipients:
            - tim.albring@scicomp.uni-kl.de
  
branches:
    only:
        - auto_doxygen_test


python:
    - 2.7
    - 3.6

addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-gui
      - graphviz


env:
    global:
        CXXFLAGS="-O3 -Wall -Wextra -Wno-unused-parameter -Wno-empty-body -Wno-format-security" 
    matrix:
        # Serial build and test
        - CONFIGURE_COMMAND="./preconfigure.py --prefix=$TRAVIS_BUILD_DIR --enable-PY_WRAPPER" TEST_SCRIPT=serial_regression.py

        # Parallel build and test
        #- CONFIGURE_COMMAND="./preconfigure.py --enable-mpi --with-cc=mpicc --with-cxx=mpicxx --prefix=$TRAVIS_BUILD_DIR --enable-PY_WRAPPER" TEST_SCRIPT=parallel_regression.py
        
        # Serial build and test for AD
        #- CONFIGURE_COMMAND="./preconfigure.py --with-cc=gcc --with-cxx=g++ --prefix=$TRAVIS_BUILD_DIR --enable-autodiff --enable-direct-diff" TEST_SCRIPT=serial_regression_AD.py

        # Parallel build and test for AD:
        #- CONFIGURE_COMMAND="./preconfigure.py --enable-mpi --with-cc=mpicc --with-cxx=mpicxx --prefix=$TRAVIS_BUILD_DIR --enable-autodiff --enable-direct-diff" TEST_SCRIPT=parallel_regression_AD.py

script:
    - echo $CONFIGURE_COMMAND
    #- python $TEST_SCRIPT

jobs:
    include:
        - stage: Deploy
          python: 2.7
          env:
              global:
                  GH_REPO_NAME=Doxygen 
                  DOXYFILE=$TRAVIS_BUILD_DIR/doc/Doxyfile
                  GH_REPO_REF=github.com/su2code/Doxygen.git
          script:
              - sh doc/generateDocumentationAndDeploy.sh

    
