# Continous Integration setup for SU2.
# Tests on the develop branch in both serial and parallel.

# To enable travis for your own branch, make sure to change the email address to receive notifications
notifications:
    email:
        recipients:
            - tim.albring@scicomp.uni-kl.de

# Change the branch name to the name of your branch
branches:
    only:
        - develop

# DO NOT TOUCH ANYTHING BELOW HERE 
dist: trusty
sudo: required

language: python

compiler:
    - gcc

python:
    - 2.7
    - 3.6

addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-gui
      - graphviz

env:
    global:
        CXXFLAGS="-O3 -Wall -Wextra -Wno-unused-parameter -Wno-empty-body -Wno-format-security" 
    matrix:
        # Serial build and test
        - CONFIGURE_COMMAND="./preconfigure.py --prefix=$TRAVIS_BUILD_DIR --enable-PY_WRAPPER"
          TEST_SCRIPT=serial_regression.py

        # Parallel build and test
        - CONFIGURE_COMMAND="./preconfigure.py --enable-mpi --with-cc=mpicc --with-cxx=mpicxx --prefix=$TRAVIS_BUILD_DIR --enable-PY_WRAPPER"
          TEST_SCRIPT=parallel_regression.py

        # Serial build and test for AD
        - CONFIGURE_COMMAND="./preconfigure.py --with-cc=gcc --with-cxx=g++ --prefix=$TRAVIS_BUILD_DIR --enable-autodiff --enable-direct-diff"
          TEST_SCRIPT=serial_regression_AD.py

        # Parallel build and test for AD:
        - CONFIGURE_COMMAND="./preconfigure.py --enable-mpi --with-cc=mpicc --with-cxx=mpicxx --prefix=$TRAVIS_BUILD_DIR --enable-autodiff --enable-direct-diff"
          TEST_SCRIPT=parallel_regression_AD.py

before_install:
    - sh travis_scripts/test/before_install.sh

install:
    - sh travis_scripts/test/install.sh

before_script:
    - sh travis_scripts/test/before_script.sh


script: 
    - travis_wait 90 sh travis_scripts/test/script.sh
              
jobs:
    include:
        - stage: doxygen
          python: 2.7
          before_install: 
              - echo 'No before install script.'
          install:
              - echo 'No install script'
          before_script:
              - echo 'No before_script script.'
          script:
              - sh travis_scripts/doxygen/script.sh
          

stages:
    - test
    - doxygen
